spring.application.name=student

#db configuration
spring.datasource.url=postgresql://dpg-cqjuhk1u0jms73do043g-a:5432/student_cnru
spring.datasource.username=student_cnru_user
spring.datasource.password=o3eJNXVlNY5uYJy8t2wEShRNXOtI4tgB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false